use crate::{Context, CordisError, EffectSet, InjectSpec, ServiceId};
use schemars::{JsonSchema, Schema, schema_for};
use serde::de::DeserializeOwned;
use std::future::Future;
use std::sync::Arc;

/// Static identity generated for a service trait.
pub trait ServiceSpec: Send + Sync + 'static {
    const NAME: &'static str;
    const ABI_HASH: [u8; 32];

    fn service_id() -> ServiceId {
        ServiceId::new(Self::NAME, Self::ABI_HASH)
    }
}

/// Static identity and payload types generated for an event declaration.
pub trait EventSpec: Send + Sync + 'static {
    type Input: Send + 'static;
    type Output: Send + 'static;

    const NAME: &'static str;
    const ABI_HASH: [u8; 32];
}

/// Compile-time dependency declaration for a native component.
pub trait DependencySet: Send + Sync + 'static {
    fn injects() -> Vec<InjectSpec>;
}

#[derive(Clone, Copy, Debug, Default)]
pub struct NoDependencies;

impl DependencySet for NoDependencies {
    fn injects() -> Vec<InjectSpec> {
        Vec::new()
    }
}

/// Immutable metadata generated by `#[cordis::component]`.
#[derive(Clone, Debug)]
pub struct ComponentDescriptor {
    pub name: &'static str,
    pub injects: Vec<InjectSpec>,
    pub config_schema: fn() -> Schema,
}

/// Metadata and associated types shared by the generated component adapter.
pub trait ComponentDefinition: Send + 'static {
    type Config: DeserializeOwned + JsonSchema + Send + Sync + 'static;
    type Deps: DependencySet;

    fn descriptor() -> &'static ComponentDescriptor;
}

/// Context passed to a native component's apply method.
#[derive(Clone, Debug)]
pub struct ComponentContext<D: DependencySet> {
    context: Context,
    deps: Arc<D>,
    effects: EffectSet,
}

impl<D: DependencySet> ComponentContext<D> {
    pub fn new(context: Context, deps: D, effects: EffectSet) -> Self {
        Self {
            context,
            deps: Arc::new(deps),
            effects,
        }
    }

    pub fn context(&self) -> &Context {
        &self.context
    }

    pub fn deps(&self) -> &D {
        &self.deps
    }

    pub fn effects(&self) -> &EffectSet {
        &self.effects
    }

    pub fn effect_set(&self) -> EffectSet {
        self.effects.clone()
    }
}

/// Effects retained after a component applies successfully.
#[derive(Clone, Debug)]
pub struct ComponentEffects {
    effects: EffectSet,
}

impl ComponentEffects {
    pub fn new(effects: EffectSet) -> Self {
        Self { effects }
    }

    pub fn effect_set(&self) -> &EffectSet {
        &self.effects
    }
}

/// Executable native component implemented by `#[cordis::component_impl]`.
pub trait Component: ComponentDefinition {
    fn apply(
        self,
        context: ComponentContext<Self::Deps>,
        config: Self::Config,
    ) -> impl Future<Output = Result<ComponentEffects, CordisError>> + Send;
}

/// Generates a JSON Schema without requiring macros to name schemars internals.
pub fn config_schema<T: JsonSchema>() -> Schema {
    schema_for!(T)
}
