use crate::{CordisError, FiberId, FiberTransition, RealmId};
use std::collections::BTreeMap;
use std::fmt;
use std::sync::Arc;

/// Stable service identity shared by native and WebAssembly components.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ServiceId {
    name: Arc<str>,
    abi_hash: [u8; 32],
}

impl ServiceId {
    pub fn new(name: impl Into<Arc<str>>, abi_hash: [u8; 32]) -> Self {
        Self {
            name: name.into(),
            abi_hash,
        }
    }

    pub fn of<K: ServiceKey>() -> Self {
        Self::new(K::NAME, K::ABI_HASH)
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub const fn abi_hash(&self) -> &[u8; 32] {
        &self.abi_hash
    }
}

impl fmt::Display for ServiceId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}@", self.name)?;
        for byte in &self.abi_hash[..4] {
            write!(formatter, "{byte:02x}")?;
        }
        Ok(())
    }
}

/// Compile-time service identity generated by `#[cordis::service]`.
pub trait ServiceKey: Send + Sync + 'static {
    const NAME: &'static str;
    const ABI_HASH: [u8; 32];
}

/// Unique slot occupied by at most one service provider.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ProviderKey {
    pub service: ServiceId,
    pub realm: RealmId,
}

impl ProviderKey {
    pub const fn new(service: ServiceId, realm: RealmId) -> Self {
        Self { service, realm }
    }
}

impl fmt::Display for ProviderKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{} in realm {}", self.service, self.realm)
    }
}

/// Whether a missing provider keeps a fiber inactive.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Requirement {
    Required,
    Optional,
}

/// One service dependency declared by a component descriptor.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct InjectSpec {
    pub service: ServiceId,
    pub requirement: Requirement,
}

impl InjectSpec {
    pub const fn required(service: ServiceId) -> Self {
        Self {
            service,
            requirement: Requirement::Required,
        }
    }

    pub const fn optional(service: ServiceId) -> Self {
        Self {
            service,
            requirement: Requirement::Optional,
        }
    }
}

/// Resolution of one declared dependency in a specific context.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResolvedInject {
    pub key: ProviderKey,
    pub provider: Option<FiberId>,
    pub requirement: Requirement,
}

/// Current dependency resolution used to derive a fiber's desired epoch.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct DependencyResolution {
    entries: Vec<ResolvedInject>,
}

impl DependencyResolution {
    pub fn new(entries: Vec<ResolvedInject>) -> Self {
        Self { entries }
    }

    pub fn entries(&self) -> &[ResolvedInject] {
        &self.entries
    }

    pub fn is_ready(&self) -> bool {
        self.entries
            .iter()
            .all(|entry| entry.provider.is_some() || entry.requirement == Requirement::Optional)
    }

    /// Freezes this resolution for component access during one load epoch.
    ///
    /// # Errors
    ///
    /// Returns [`CordisError::InactiveDependency`] if a required provider is absent.
    pub fn commit(&self) -> Result<CommittedView, CordisError> {
        if let Some(missing) = self
            .entries
            .iter()
            .find(|entry| entry.requirement == Requirement::Required && entry.provider.is_none())
        {
            return Err(CordisError::InactiveDependency {
                key: missing.key.clone(),
            });
        }

        Ok(CommittedView {
            entries: self
                .entries
                .iter()
                .cloned()
                .map(|entry| (entry.key.service.clone(), entry))
                .collect(),
        })
    }
}

/// Immutable provider selection used throughout one component load epoch.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct CommittedView {
    entries: BTreeMap<ServiceId, ResolvedInject>,
}

impl CommittedView {
    /// Looks up the provider selected for a declared dependency.
    ///
    /// # Errors
    ///
    /// Returns [`CordisError::UndeclaredDependency`] for an unknown service.
    pub fn lookup(&self, service: &ServiceId) -> Result<Option<FiberId>, CordisError> {
        self.entries
            .get(service)
            .map(|entry| entry.provider)
            .ok_or_else(|| CordisError::UndeclaredDependency {
                service: service.clone(),
            })
    }

    pub fn entries(&self) -> impl ExactSizeIterator<Item = &ResolvedInject> {
        self.entries.values()
    }
}

/// Provider-store mutation result, already narrowed to affected consumers.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RegistryChange {
    pub key: ProviderKey,
    pub affected: Vec<FiberId>,
    pub transitions: Vec<FiberTransition>,
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestService;

    impl ServiceKey for TestService {
        const NAME: &'static str = "test.service";
        const ABI_HASH: [u8; 32] = [0xAB; 32];
    }

    #[test]
    fn typed_identity_contains_name_and_abi_hash() {
        let id = ServiceId::of::<TestService>();
        assert_eq!(id.name(), "test.service");
        assert_eq!(id.abi_hash(), &[0xAB; 32]);
        assert_eq!(id.to_string(), "test.service@abababab");
    }
}
